name: Shell commands

on: [push]

jobs:
  run-shell-ronny:
    name: primer job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file ./personas/pom.xml
      - name: set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:            
            aws-region: us-west-1