name: Shell commands

on: [push]

jobs:
  run-shell-ronny:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hola Ronny actions"
      - name: multiline script
        run: |
          node -v
          npm -v
